controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_1_joint
      - left_2_joint
      - left_3_joint
      - left_4_joint
      - left_5_joint
      - left_6_joint
      - left_7_joint
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_1_joint
      - right_2_joint
      - right_3_joint
      - right_4_joint
      - right_5_joint
      - right_6_joint
      - right_7_joint
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_8_joint
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_8_joint
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []