left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_1_joint
    - left_2_joint
    - left_3_joint
    - left_4_joint
    - left_5_joint
    - left_6_joint
    - left_7_joint
  gains:
    left_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_1_joint
    - right_2_joint
    - right_3_joint
    - right_4_joint
    - right_5_joint
    - right_6_joint
    - right_7_joint
  gains:
    right_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_8_joint
  gains:
    left_8_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_8_joint
  gains:
    right_8_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1